/**
 * Expo config plugin — wires up the Android kiosk surface area:
 *
 *   1. RECEIVE_BOOT_COMPLETED permission.
 *   2. A BootReceiver broadcast receiver that re-launches MainActivity
 *      after a power cycle (closes agenda item #3 — Auto-start after
 *      device reboot).
 *   3. MainActivity flags for kiosk-style behaviour:
 *        - `android.intent.category.HOME` so the app can be set as the
 *          device's home launcher (closes agenda item #5 — Android
 *          kiosk configuration).
 *        - `android:resizeableActivity="false"` and locked-orientation
 *          attributes complement what `expo-screen-orientation` sets at
 *          runtime.
 *
 * This plugin is applied at `expo prebuild` / EAS-build time — Expo Go
 * (`npm run start`) does NOT run native code, so during development
 * none of these settings take effect. That's fine: development happens
 * in Expo Go, deployment happens via a prebuilt APK.
 *
 * The boot-receiver Kotlin file itself is also generated by this
 * plugin (`withDangerousMod`) — it's a 12-line broadcast receiver
 * that fires a `LAUNCHER` intent for MainActivity when it receives
 * BOOT_COMPLETED.
 */

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const BOOT_RECEIVER_KOTLIN = `package %PKG%

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent

/**
 * Auto-launches MainActivity after the device finishes booting.
 *
 * Triggered by the BOOT_COMPLETED broadcast (which requires the
 * RECEIVE_BOOT_COMPLETED permission). The launch intent uses
 * FLAG_ACTIVITY_NEW_TASK because we're outside any activity context
 * and FLAG_ACTIVITY_CLEAR_TOP so any stale instance from a previous
 * boot is cleared.
 */
class BootReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    if (intent.action == Intent.ACTION_BOOT_COMPLETED) {
      val launchIntent = context.packageManager
        .getLaunchIntentForPackage(context.packageName)
      launchIntent?.let {
        it.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
        context.startActivity(it)
      }
    }
  }
}
`;

/** Manifest mutation: add boot permission + receiver + MainActivity flags. */
function withBootReceiverManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    const pkg = config.android?.package ?? cfg.android?.package;
    if (!pkg) {
      throw new Error('withKiosk: android.package must be set in app.json.');
    }

    // 1. Add RECEIVE_BOOT_COMPLETED permission.
    manifest['uses-permission'] = manifest['uses-permission'] ?? [];
    const hasPerm = manifest['uses-permission'].some(
      (p) => p.$['android:name'] === 'android.permission.RECEIVE_BOOT_COMPLETED',
    );
    if (!hasPerm) {
      manifest['uses-permission'].push({
        $: { 'android:name': 'android.permission.RECEIVE_BOOT_COMPLETED' },
      });
    }

    // 2. Add BootReceiver inside <application>.
    const app = manifest.application?.[0];
    if (!app) throw new Error('withKiosk: <application> tag missing.');

    app.receiver = app.receiver ?? [];
    const hasReceiver = app.receiver.some(
      (r) => r.$['android:name'] === `${pkg}.BootReceiver`,
    );
    if (!hasReceiver) {
      app.receiver.push({
        $: {
          'android:name': `${pkg}.BootReceiver`,
          'android:enabled': 'true',
          'android:exported': 'true',
          'android:permission': 'android.permission.RECEIVE_BOOT_COMPLETED',
        },
        'intent-filter': [{
          action: [{ $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
        }],
      });
    }

    // 3. MainActivity: add HOME category + nonresizable for kiosk use.
    const mainActivity = app.activity?.find(
      (a) => a.$['android:name'] === '.MainActivity',
    );
    if (mainActivity) {
      mainActivity.$['android:resizeableActivity'] = 'false';
      mainActivity.$['android:launchMode'] = 'singleTask';
      // Add HOME + DEFAULT categories to the LAUNCHER intent filter so
      // the OS will offer this app as a launcher (kiosks set it as
      // default via "Settings → Apps → Default apps → Home app").
      const launcherFilter = mainActivity['intent-filter']?.find(
        (f) => f.action?.some(
          (a) => a.$['android:name'] === 'android.intent.action.MAIN',
        ),
      );
      if (launcherFilter) {
        launcherFilter.category = launcherFilter.category ?? [];
        const hasHome = launcherFilter.category.some(
          (c) => c.$['android:name'] === 'android.intent.category.HOME',
        );
        if (!hasHome) {
          launcherFilter.category.push({
            $: { 'android:name': 'android.intent.category.HOME' },
          });
        }
        const hasDefault = launcherFilter.category.some(
          (c) => c.$['android:name'] === 'android.intent.category.DEFAULT',
        );
        if (!hasDefault) {
          launcherFilter.category.push({
            $: { 'android:name': 'android.intent.category.DEFAULT' },
          });
        }
      }
    }

    return cfg;
  });
}

/** Drop the BootReceiver.kt file into the prebuilt Android project. */
function withBootReceiverKotlin(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const pkg = config.android?.package ?? cfg.android?.package;
      if (!pkg) return cfg;
      const projectRoot = cfg.modRequest.platformProjectRoot;
      const kotlinDir = path.join(
        projectRoot, 'app', 'src', 'main', 'java',
        ...pkg.split('.'),
      );
      fs.mkdirSync(kotlinDir, { recursive: true });
      fs.writeFileSync(
        path.join(kotlinDir, 'BootReceiver.kt'),
        BOOT_RECEIVER_KOTLIN.replace('%PKG%', pkg),
      );
      return cfg;
    },
  ]);
}

module.exports = function withKiosk(config) {
  config = withBootReceiverManifest(config);
  config = withBootReceiverKotlin(config);
  return config;
};
